language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t react -f ./client/Dockerfile.dev ./client
script:
  - docker run react npm run test -- --coverage
after_success:
  - docker build -t varundunga/client ./client
  - docker build -t varundunga/server ./server
  - docker build -t varundunga/worker ./worker
  - docker build -t varundunga/nginx  ./nginx
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push varundunga/client
  - docker push varundunga/server
  - docker push varundunga/worker
  - docker push varundunga/nginx
deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "multidocker"
  env: "Multidocker-env-1"
  bucket_name: "elasticbeanstalk-ap-south-1-501352840692"
  bucket_path: "multidocker"
  on: 
    branch: master
  access_key_id:
    secure: "$AWS_ID"
  secret_access_key:
    secure: "$AWS_PWD"  
